"use client";
import { useEffect, useState } from "react";
import { Download, RefreshCw, ShieldCheck } from "lucide-react";

type Group={id:string;groupName:string;status:string;score:number;percentage:number;correctCount:number;level:string;attempts:number;retakeAllowed:number;completedAt:string|null;members:{fullName:string;dni:string}[]};
export default function Admin(){const [groups,setGroups]=useState<Group[]>([]),[ready,setReady]=useState(false),[auth,setAuth]=useState(false),[error,setError]=useState("");
 async function load(){const r=await fetch("/api/admin/results");if(r.status===401){setAuth(false);setReady(true);return}const d=await r.json();setGroups(d.groups||[]);setAuth(true);setReady(true)}
 useEffect(()=>{load()},[]);
 async function login(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError("");const f=new FormData(e.currentTarget),r=await fetch("/api/admin/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({username:f.get("username"),password:f.get("password")})});if(!r.ok){setError("Usuario o contraseña incorrectos.");return}await load()}
 async function retake(id:string,allowed:boolean){await fetch("/api/admin/retake",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({groupId:id,allowed})});await load()}
 function csv(){const rows=[["Grupo","Integrantes","DNI","Estado","Aciertos","Porcentaje","Puntaje","Nivel","Intentos","Fecha"],...groups.map(g=>[g.groupName,g.members.map(m=>m.fullName).join(" | "),g.members.map(m=>m.dni).join(" | "),g.status,String(g.correctCount),String(g.percentage),String(g.score),g.level,String(g.attempts),g.completedAt||""])];const content="\ufeff"+rows.map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(",")).join("\n"),u=URL.createObjectURL(new Blob([content],{type:"text/csv;charset=utf-8"})),a=document.createElement("a");a.href=u;a.download="Resultados_Gobernanza_IA_AADTC.csv";a.click();URL.revokeObjectURL(u)}
 if(!ready)return <main className="adminShell">Cargando…</main>;
 if(!auth)return <main className="adminShell"><div className="adminHeader"><img src="/aadtc-logo.png" alt="AADTC"/><a href="/">Volver al examen</a></div><section className="login card"><ShieldCheck size={34}/><h1>Control docente</h1><p>Acceso restringido a resultados y recuperatorios.</p><form onSubmit={login}><label>Usuario<input name="username" required autoComplete="username"/></label><label>Contraseña<input name="password" type="password" required autoComplete="current-password"/></label>{error&&<p className="error">{error}</p>}<button className="primary">Ingresar</button></form></section></main>;
 const completed=groups.filter(g=>g.status==="completed"),passed=completed.filter(g=>g.percentage>=60),average=completed.length?Math.round(completed.reduce((n,g)=>n+g.percentage,0)/completed.length):0;
 return <main className="adminShell"><div className="adminHeader"><img src="/aadtc-logo.png" alt="AADTC"/><a href="/">Ir al examen</a></div><section className="dashboard card"><div className="toolbar"><div><h1>Resultados de grupos</h1><p>Registro para la gestión académica y administrativa.</p></div><div><button onClick={load}><RefreshCw size={16}/> Actualizar</button> <button onClick={csv}><Download size={16}/> Exportar CSV</button></div></div><div className="stats"><div className="stat"><b>{groups.length}</b><span>grupos registrados</span></div><div className="stat"><b>{completed.length}</b><span>entregas</span></div><div className="stat"><b>{passed.length}</b><span>aprobados</span></div><div className="stat"><b>{average}%</b><span>promedio</span></div></div><div className="tableWrap"><table><thead><tr><th>Grupo e integrantes</th><th>Estado</th><th>Resultado</th><th>Intentos</th><th>Fecha</th><th>Recuperatorio</th></tr></thead><tbody>{groups.map(g=><tr key={g.id}><td><strong>{g.groupName}</strong>{g.members.map(m=><div key={m.dni}>{m.fullName} · DNI {m.dni}</div>)}</td><td><span className="badge">{g.status==="completed"?"Entregado":"En curso"}</span></td><td>{g.status==="completed"?<><strong>{g.percentage}% · {g.level}</strong><div>{g.correctCount}/12 · {g.score} pts</div></>:"—"}</td><td>{g.attempts}</td><td>{g.completedAt?new Date(g.completedAt).toLocaleString("es-AR"):"—"}</td><td>{g.status==="completed"?<button className="retake" onClick={()=>retake(g.id,!g.retakeAllowed)}>{g.retakeAllowed?"Revocar":"Habilitar"}</button>:"—"}</td></tr>)}</tbody></table>{!groups.length&&<p>No hay resultados registrados.</p>}</div></section></main>}
