"use client";
import { useEffect, useState } from "react";
import { Plus, Trash2, Download, Printer, Gauge } from "lucide-react";

const questions=[
 ["Fundamentos","La dirección anuncia “no discriminaremos”, pero nadie puede detener el sistema y no existen controles.","¿Qué falta para convertir la intención en una práctica controlable?",["Una campaña interna sobre valores.","Gobernanza con responsables, controles, evidencia y escalamiento.","Delegar toda responsabilidad al proveedor."]],
 ["IA sombra","Un analista pega contratos confidenciales en una IA pública no aprobada.","¿Cuál es la respuesta más completa?",["Borrar el historial.","Prohibir toda IA indefinidamente.","Usos permitidos, entorno institucional, DLP, capacitación y monitoreo."]],
 ["ISO/IEC 42001","La empresa quiere ordenar la gestión de IA.","¿Qué aporta ISO/IEC 42001?",["Un sistema de gestión organizacional para la IA.","Garantiza cada respuesta del modelo.","Sustituye todas las leyes."]],
 ["Argentina","El equipo sostiene que sin una ley integral de IA no hay obligaciones.","¿Qué criterio debe adoptar el comité?",["Aceptar esa conclusión.","Evaluar datos, consumidores, sector, contratos y controles vigentes.","Aplicar solo el AI Act europeo."]],
 ["Capas","Existe documentación técnica, pero negocio no definió propósito y Legal no revisó los datos.","¿Qué diagnóstico corresponde?",["La documentación alcanza.","Falta integrar las capas estratégica, organizacional, operativa, técnica y de cumplimiento.","Solo falta monitoreo."]],
 ["Tres líneas","Auditoría interna es dueña del riesgo y aprueba el despliegue.","¿Cómo debe corregirse?",["Negocio posee el riesgo; Riesgo/Legal supervisan; Auditoría evalúa independientemente.","Auditoría opera el sistema.","El proveedor ocupa las tres líneas."]],
 ["Ciclo de vida","Un asistente cambia de modelo, suma fuentes y ahora ejecuta acciones.","¿Qué protege mejor el ciclo de vida?",["Mantener la aprobación original.","Reevaluar impacto, riesgo, pruebas, permisos y autorización.","Revisar solo el costo."]],
 ["Riesgo","El riesgo residual sigue por encima del apetito aprobado.","¿Qué debe ocurrir?",["Desplegar porque hay controles.","Ocultarlo en un anexo.","Mitigar, transferir, evitar o escalar para aceptación autorizada."]],
 ["IA agéntica","Un agente aprueba reembolsos y modifica registros con privilegios amplios.","¿Qué controles son prioritarios?",["Más creatividad en el prompt.","Mínimo privilegio, límites, confirmación, trazabilidad y detención.","Una encuesta de satisfacción."]],
 ["Ciberseguridad","Una función crítica con IA eliminará el modo manual.","¿Cuál es el enfoque adecuado?",["Zero Trust, segmentación, monitoreo, incidentes y modo seguro.","Contraseña compartida.","Delegar resiliencia al modelo."]],
 ["Hoja de ruta","La organización inicia un plan de 90 días.","¿Qué secuencia es razonable?",["Certificarse antes de inventariar.","Inventariar; definir roles y políticas; pilotear controles y métricas.","Comprar tecnología y postergar gobernanza."]],
 ["Valor","El directorio pregunta cómo saber si la gobernanza genera valor.","¿Qué respuesta muestra madurez?",["Contar documentos.","Eliminar controles.","Medir incidentes, aprobación, adopción segura, desempeño y negocio."]]
] as const;
type Member={fullName:string;dni:string;verificationCode?:string};

export default function Home(){
 const [stage,setStage]=useState<"setup"|"quiz"|"result">("setup"),[groupName,setGroupName]=useState(""),[members,setMembers]=useState<Member[]>([{fullName:"",dni:""}]),[groupId,setGroupId]=useState(""),[index,setIndex]=useState(0),[answers,setAnswers]=useState<number[]>([]),[selected,setSelected]=useState<number|null>(null),[result,setResult]=useState<any>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const updateMember=(i:number,key:keyof Member,value:string)=>setMembers(members.map((m,j)=>j===i?{...m,[key]:value}:m));
 async function start(e:React.FormEvent){e.preventDefault();setError("");setBusy(true);const r=await fetch("/api/groups/start",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({groupName,members})});const d=await r.json();setBusy(false);if(!r.ok){setError(d.error);return}setGroupId(d.groupId);setStage("quiz")}
 async function confirm(){if(selected===null)return;const next=[...answers,selected];if(index<questions.length-1){setAnswers(next);setIndex(index+1);setSelected(null);return}setBusy(true);const r=await fetch("/api/groups/complete",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({groupId,answers:next})});const d=await r.json();setBusy(false);if(!r.ok){setError(d.error);return}setAnswers(next);setResult(d);setStage("result")}
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const ac=new AbortController();ctx.registerTool({name:"open_teacher_control",title:"Abrir control docente",description:"Navega al panel docente de resultados y recuperatorios.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>{location.href="/admin";return{opened:true}}},{signal:ac.signal});return()=>ac.abort()},[]);
 if(stage==="setup")return <main className="shell"><header><img src="/aadtc-logo.png" alt="AADTC"/><a href="/admin">Control docente</a></header><section className="hero card"><div className="heroCopy"><span>Evaluación aplicada · Módulo 6</span><h1>Gobernanza de IA: decisiones con evidencia.</h1><p>Cada grupo dispone de un único intento. Los resultados quedan registrados para la gestión académica.</p></div><form onSubmit={start} className="form"><label>Grupo<input required minLength={2} value={groupName} onChange={e=>setGroupName(e.target.value)} placeholder="Ej.: Grupo Delta"/></label><div className="membersHead"><strong>Integrantes</strong><small>Apellido y nombres + DNI</small></div>{members.map((m,i)=><div className="memberRow" key={i}><input aria-label={`Apellido y nombres del integrante ${i+1}`} required value={m.fullName} onChange={e=>updateMember(i,"fullName",e.target.value)} placeholder="Apellido y nombres"/><input aria-label={`DNI del integrante ${i+1}`} required inputMode="numeric" pattern="[0-9]{7,9}" value={m.dni} onChange={e=>updateMember(i,"dni",e.target.value.replace(/\D/g,""))} placeholder="DNI"/>{i>0&&<button type="button" className="icon danger" onClick={()=>setMembers(members.filter((_,j)=>j!==i))} aria-label="Quitar integrante"><Trash2/></button>}</div>)}<button type="button" className="add" onClick={()=>setMembers([...members,{fullName:"",dni:""}])}><Plus/> Agregar integrante</button>{error&&<p className="error">{error}</p>}<button className="primary" disabled={busy}>{busy?"Verificando…":"Comenzar examen"}</button></form></section></main>;
 if(stage==="quiz"){const q=questions[index];return <main className="shell"><div className="hud card"><div><strong>{groupName}</strong><small>Pregunta {index+1} de 12</small></div><div className="bar"><i style={{width:`${index/12*100}%`}}/></div><b>{answers.length*100} pts</b></div><section className="question card"><span className="topic">{q[0]}</span><div className="scenario">{q[1]}</div><h2>{q[2]}</h2><div className="options">{q[3].map((o,i)=><button key={o} onClick={()=>setSelected(i)} className={selected===i?"selected":""}><b>{String.fromCharCode(65+i)}</b>{o}</button>)}</div>{error&&<p className="error">{error}</p>}<button className="primary next" disabled={selected===null||busy} onClick={confirm}>{index===11?"Entregar examen":"Confirmar y continuar"}</button></section></main>}
 return <Result result={result} groupName={groupName} members={result?.members||members}/>;
}

function Result({result,groupName,members}:{result:any;groupName:string;members:Member[]}){
 const date=new Intl.DateTimeFormat("es-AR",{day:"numeric",month:"long",year:"numeric"}).format(new Date());
 async function data(src:string){const b=await(await fetch(src)).blob();return await new Promise<string>((ok,no)=>{const f=new FileReader();f.onload=()=>ok(String(f.result));f.onerror=no;f.readAsDataURL(b)})}
 async function certificate(m:Member){
  if(!m.verificationCode)return;
  const [{jsPDF},QR,logo,sign]=await Promise.all([import("jspdf"),import("qrcode"),data("/aadtc-logo.png"),data("/firma-ricardo-canaveri.png")]);
  const verifyUrl=`${window.location.origin}/certificado/${m.verificationCode}`;
  const qr=await QR.toDataURL(verifyUrl,{errorCorrectionLevel:"H",margin:1,width:500,color:{dark:"#18345fff",light:"#ffffffff"}});
  const pdf=new jsPDF({orientation:"landscape",unit:"mm",format:"a4"}),w=297,c=w/2;
  pdf.setDrawColor(35,63,115);pdf.setLineWidth(1.4);pdf.rect(6,6,285,198);pdf.setLineWidth(.35);pdf.rect(9,9,279,192);
  pdf.addImage(logo,"PNG",91,13,115,28,undefined,"FAST");pdf.setTextColor(24,52,95);
  pdf.setFont("times","bold");pdf.setFontSize(15);pdf.text("Curso Anual de Profundización en Derecho de las Telecomunicaciones,",c,51,{align:"center"});pdf.text("Servicios de Comunicación Audiovisual y Tecnologías de la Información y las Comunicaciones",c,58,{align:"center"});
  pdf.setFont("helvetica","bold");pdf.setFontSize(13);pdf.text("MÓDULO 6: EVOLUCIÓN Y DESAFÍO DE LAS TICS",c,70,{align:"center"});
  pdf.setFont("helvetica","normal");pdf.setFontSize(11);pdf.text("Diseño, gestión responsable y Gobernanza de la IA: Retos y Oportunidades en el sector TIC.",c,78,{align:"center"});
  pdf.setFont("times","normal");pdf.setFontSize(13);pdf.text("Por cuanto",c,91,{align:"center"});
  pdf.setFont("times","bold");pdf.setFontSize(m.fullName.length>42?20:23);pdf.text(m.fullName,c,103,{align:"center",maxWidth:250});
  pdf.setFont("times","normal");pdf.setFontSize(12);pdf.text(`DNI ${m.dni} · Integrante de ${groupName}`,c,113,{align:"center",maxWidth:250});
  pdf.setFontSize(13);pdf.text("ha aprobado los contenidos teóricos y prácticos de la capacitación brindada por AADTC.",c,126,{align:"center",maxWidth:260});
  pdf.setFontSize(11);pdf.text(`Ciudad Autónoma de Buenos Aires, ${date}.`,c,139,{align:"center"});
  pdf.addImage(qr,"PNG",52,143,29,29,undefined,"FAST");pdf.setFont("helvetica","normal");pdf.setFontSize(6.5);pdf.text("VERIFICAR CERTIFICADO",66.5,176,{align:"center"});pdf.setFontSize(5.5);pdf.text(m.verificationCode.slice(0,16).toUpperCase(),66.5,180,{align:"center"});
  pdf.addImage(sign,"PNG",126,142,45,24,undefined,"FAST");pdf.setLineWidth(.35);pdf.line(116,166,181,166);
  pdf.setFont("times","bold");pdf.setFontSize(11);pdf.text("Mg. Ing. Ricardo Alcides Canaveri",c,172,{align:"center"});pdf.setFont("times","normal");pdf.setFontSize(9);pdf.text("Profesor",c,177,{align:"center"});
  pdf.save(`Certificado_${m.fullName.replace(/[^a-z0-9]+/gi,"_")}.pdf`);
 }
 return <main className="shell"><section className="result card"><Gauge size={38}/><h1>{result.passed?"Examen aprobado":"Resultado registrado"}</h1><p>{groupName} · {result.correct}/12 respuestas correctas</p><div className="meter"><div className="needle" style={{left:`${result.percentage}%`}}/><div className="colors"/></div><div className="meterLabels"><span>Inicial</span><span>En desarrollo</span><span>Competente</span><span>Avanzado</span></div><strong className="percent">{result.percentage}% · {result.level}</strong>{result.passed?<><div className="certList"><h2>Certificados individuales</h2><p>Descargá un certificado por cada integrante.</p>{members.map(m=><button key={m.dni} onClick={()=>certificate(m)}><Download/> {m.fullName} · DNI {m.dni}</button>)}</div></>:<p className="error">El certificado se habilita a partir del 60 %. El docente puede autorizar un nuevo intento.</p>}<div className="resultActions"><button onClick={()=>window.print()}><Printer/> Imprimir resultado</button><a href="/">Finalizar</a></div></section></main>
}
